### PR TITLE
Remove sitemap plugin

### PR DESCRIPTION
**Pull request by PanSpagetka**
If I remember correctly there was meeting some time ago, where we concluded that sitemaps are kind of useless, because urls are gated by authentication. So I think we could delete this plugin. I am opening this PR to opened discussion whether there is any value in maintaining this or not.  Please add anyone who could have an relevant opinion about this.
@RedHatInsights/platform-experience

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]

**Comment by karelhala** [comment]
It's kind of a bummer :disappointed: I would personally keep the plugin in place, just not use it...

**Comment by karelhala** [comment]
Roping in this big group @RedHatInsights/advisor-ui-reviewers, any objections to remove this plugin?

**Comment by Hyperkid123** [comment]
@karelhala  I am gonna merge it later today. Just let me know if you are against it.

**Comment by karelhala** [comment]
@Hyperkid123 fine by me

**Review by karelhala — APPROVED** [review]

**Pull request merged**
