### PR TITLE
create helper function to fetch data with concurrent requests

### PR DESCRIPTION
**Pull request by mkholjuraev**
This adds a simple, but useful helper function to utils package. It will help us to fetch a huge amount of data using paginated requests. Additionally, those paginated requests can be done in a certain number of concurrent API calls.

### CODE REVIEW

**Review by Hyperkid123 — COMMENTED** [review]
Do we need the `p-all` and `p-map` dependency? In this case, we are dealing with just a simple que.

I am also a bit curious about why you need to limit the number of concurrent requests at all?

**Comment by mkholjuraev** [comment]
@Hyperkid123 thank you for having a look. I think they will be useful to avoid AKAMAI blocks when there are 10k items to be fetched. As you know if we do not limit concurrent requests, AKAMAI will block after a short time. Let me know if this is not needed

**Comment by Hyperkid123** [comment]
> I think they will be useful to avoid AKAMAI blocks when there are 10k items to be fetched.

Oh, one more question. Why is it that the UI requires 10k of records? Rendering anything with 10k items (table for example) is never going to end up with good UX unless the view is virtualized.

**Comment by mkholjuraev** [comment]
Yup, this is one of the major issues on the UI that we face. When for example, a customer selects all existing advisories to be remediated, there is too much data to be fetched on the UI. Another example is when customers export reports. Maybe, I am exaggerating a bit, but I have seen sometimes this indeed happens

**Comment by mkholjuraev** [comment]
The ideal solution for the remediation issue would be to do changes in the architectural level, but it is requires a decent amount of effort. Discussions on this have been taken place even now.

**Comment by Hyperkid123** [comment]
> The ideal solution for the remediation issue would be to do changes in the architectural level, but it is requires a decent amount of effort. Discussions on this have been taken place even now.

Yeah, I think the screens should be revisited then. I am not going to block your features, but I'd like it if the problem was properly sorted out at some point. These kinds of "optimizations" should never be required.

**Comment by bastilian** [comment]
@Hyperkid123 One main area that we have been using these hooks or similar solutions are exports, like CSV, JSON and PDF.

**Comment by mkholjuraev** [comment]
@Hyperkid123 just wanted to remind you about this.

**Comment by Hyperkid123** [comment]
@mkholjuraev the CI is still failing.

**Comment by mkholjuraev** [comment]
@Hyperkid123 fixed. PTAL

**Review by gkarat — APPROVED** [review]
LGTM. I think we can merge and release it now

**Review by gkarat — CHANGES_REQUESTED** [review]
Oops, there are some conflicts. Can we resolve them? @mkholjuraev otherwise, everything looks good

**Comment by mkholjuraev** [comment]
@gkarat thanks for having a look. Conflicts are resolved now

**Pull request merged**
