### PR TITLE
update cloudigrade (subscription watch) policy…

### PR DESCRIPTION
**Pull request by infinitewarp**
…to use DeleteTrail instead of StopLogging.

https://gitlab.com/cloudigrade/cloudigrade/-/issues/687

### CODE REVIEW

**Comment by katherine-black** [comment]
Or, OR! So we never have to open one of these, just maybe have it pull the sysconfig policy from the sysconfig endpoint, documented here: https://gitlab.com/cloudigrade/cloudigrade/-/blob/master/docs/rest-api-examples.rst#L1461

**Comment by infinitewarp** [comment]
Changing the hard-coded JSON is about as far as I'm personally comfortable messing with this JavaScript component, but if any _other_ contributors to this project would be willing to help out on @katherine-black's suggestion, that would be great! 🙂

**Comment by cdcabrera** [comment]
@karelhala @ryelo when you get a moment need a quick review

**Comment by karelhala** [comment]
Ping @rvsia

**Comment by rvsia** [comment]
@infinitewarp @katherine-black I can take a look.

**Comment by rvsia** [comment]
@infinitewarp @katherine-black addressed here https://github.com/RedHatInsights/frontend-components/pull/617

**Pull request merged**
