### PR TITLE
Advisor report table to have sticky header

### PR DESCRIPTION
**Pull request by AllenBW**
fixes https://issues.redhat.com/browse/ADVISOR-1677

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@AllenBW did you tried it in a stable env? I remember other apps had issues with the sticky header in old chrome. You might have to add a little chrome 1 workaround if it does not.

**Comment by AllenBW** [comment]
prod stable has it for advisor recommendations, topics, and systems, havent seen any issues

**Review by Hyperkid123 — APPROVED** [review]

**Comment by AllenBW** [comment]
Geez, ok I mispoke, or misread, yer right @Hyperkid123 only workin in beta, but workin in all da beta, chrome safari ff n since that env will be released to stable soon, m ok just leaving it as is, without the shim thing, n seein this show up when the change happens 🤗

**Comment by Hyperkid123** [comment]
Yeah, the "workaround" has to be done in apps anyway.

**Pull request merged**
