### PR TITLE
Add settings for proxy

### PR DESCRIPTION
**Pull request by rvsia**
## useProxy

The config provide a way to run your applications without using insights-proxy. Just add `useProxy: true` to your configuration.

```jsx
const { config: webpackConfig, plugins } = config({
  rootFolder: resolve(__dirname, '../'),
  debug: true,
  useFileHash: false,
  deployment: process.env.BETA ? 'beta/apps' : 'apps',
  useProxy: true,
});
```

And run your application with following command:

```shell
NODE_ENV=development BETA=true webpack serve --config config/dev.webpack.config.js
```

*Path to config can be different*

Then you will find your application running on `https://ci.foo.redhat.com:1337/beta/...`. This works only with **Chrome 2** ready applications.

You can change the environment by setting `betaEnv`, but unless the targeted environment is using Chrome 2.0, it won't work correctly.

### localChrome

You can also easily run you application with a local build of Chrome by adding `localChrome: <absolute_path_to_chrome_build_folder>`.

```jsx
  rootFolder: resolve(__dirname, '../'),
  debug: true,
  useFileHash: false,
  deployment: process.env.BETA ? 'beta/apps' : 'apps',
  useProxy: true,
  localChrome: process.env.INSIGHTS_CHROME,
});
```

```shell
INSIGHTS_CHROME=/Users/rvsiansk/insights-project/insights-chrome/build/
```

To check what the proxy is doing with your local chrome settings you can set `proxyVerbose: true`.

### Custom proxy settings

You can add any additional custom proxy configuration. See [Webpack documentation](https://webpack.js.org/configuration/dev-server/#devserverproxy). Please, provide your configuration as an array of object containing `context` property.

*Example*:

```jsx
const { config: webpackConfig, plugins } = config({
  rootFolder: resolve(__dirname, '../'),
  debug: true,
  useFileHash: false,
  deployment: process.env.BETA ? 'beta/apps' : 'apps',
  useProxy: true,
  localChrome: process.env.INSIGHTS_CHROME,
  customProxy: [
    {
      context: (path) => path.includes('/api/'),
      target: 'https://qa.cloud.redhat.com',
      secure: false,
      changeOrigin: true,
      autoRewrite: true,
      ws: true,
    },
  ],
});
```

This configuration will redirect all API requests to QA environment, so you can check CI UI with QA data.

### CODE REVIEW

**Review by karelhala — COMMENTED** [review]
Awesome effort! Thank you for rasing this up. What about option to consume additional paths? For instance custom cloud-services-config would need custom proxy, which is kinda dumb. How about consuming a config similiar to insights proxy?

**Comment by rvsia** [comment]
@karelhala Providing custom routes is possible via `customProxy` attribute. We could make some function, that will take the spandx config and convert it to the configuration that webpack accepts, it should be pretty simple - however serving local files is not so straightforward. However, I would like to focus on the basic use-case now, which should be sufficient for frontend development.

**Comment by karelhala** [comment]
@rvsia yeah I am not refering to serving local files, I'd still imagine users would spin new http server in the config folder and just have option to pass new config to the webpack config.

**Comment by Hyperkid123** [comment]
@karelhala I think we should merge this since it's an opt-in feature and add additional configuration is second run. It gives an opportunity to test out the config in everyday use.

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
