### PR TITLE
[Chore] - Updated Eslint to v8.9.0

### LINKED ISSUE #1410: Update eslint to v8.x.x
The common eslint config still depends on eslint v7, but most apps should use v8 as it is the lts.

https://github.com/RedHatInsights/frontend-components/tree/master/packages/eslint-config

If an app is using npm@7 we have peer dependencies warnings and we have to use the force flag which may cause issues.

### TODO
- [ ] any package using eslint@7 should be updated to use eslint@7
- [ ] remove force install in create-crc-app script: https://github.com/RedHatInsights/frontend-components/blob/master/packages/create-crc-app/bin/create-crc-app.js#L52

cc @adithyaakrishna

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <adikrish@redhat.com>

**Description:**
This PR Fixes #1410

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@Hyperkid123 I have updated `eslint-plugin-react` to the latest version as it was warning about some peerDependencies Issue

**Warning Screenshot:**

Screenshot 2022-02-24 at 10 58 43 PM

**Comment by Hyperkid123** [comment]
@adithyaakrishna hmm I have just tried this PR locally and I am able to install it just fine. No warnings. When I output the installed eslint packages I also get no errors

```sh
npm ls eslint
@redhat-cloud-services/frontend-components-root@0.0.1 /home/martin/insights/frontend-components
├─┬ @babel/eslint-parser@7.14.3
│ └── eslint@8.9.0 deduped
├─┬ @redhat-cloud-services/eslint-config-redhat-cloud-services@1.2.1 -> ./packages/eslint-config
│ ├─┬ eslint-plugin-prettier@3.4.0
│ │ └── eslint@8.9.0 deduped
│ └── eslint@8.9.0 deduped
├─┬ @typescript-eslint/eslint-plugin@5.7.0
│ ├─┬ @typescript-eslint/experimental-utils@5.7.0
│ │ └── eslint@8.9.0 deduped
│ └── eslint@8.9.0 deduped
├─┬ @typescript-eslint/parser@5.7.0
│ └── eslint@8.9.0 deduped
├─┬ docs@0.1.0 -> ./packages/docs
│ └─┬ eslint-config-next@11.1.4
│   ├─┬ @typescript-eslint/parser@4.33.0
│   │ └── eslint@7.32.0 deduped
│   ├─┬ eslint-import-resolver-typescript@2.5.0
│   │ └── eslint@8.9.0 deduped
│   ├─┬ eslint-plugin-jsx-a11y@6.5.1
│   │ └── eslint@8.9.0 deduped
│   ├─┬ eslint-plugin-react-hooks@4.3.0
│   │ └── eslint@8.9.0 deduped
│   └── eslint@7.32.0
├─┬ eslint-config-prettier@8.3.0
│ └── eslint@8.9.0 deduped
├─┬ eslint-plugin-import@2.25.4
│ └── eslint@8.9.0 deduped
├─┬ eslint-plugin-react@7.28.0
│ └── eslint@8.9.0 deduped
└─┬ eslint@8.9.0
  └─┬ eslint-utils@3.0.0
    └── eslint@8.9.0 deduped
```

**Comment by Hyperkid123** [comment]
Can you try running `npm run clean` and installing the dependencies again?

**Comment by adithyaakrishna** [comment]
@Hyperkid123 I have updated  `eslint-config-next`, `@typescript-eslint/parser`, and `@typescript-eslint/eslint-plugin` as they were dependent on the older eslint version. After that I ran `npm run clean`, `npm install` and it ran successfully without any issues.

**Review by Hyperkid123 — COMMENTED** [review]
Can you also fix the new eslint issues? They probably popped up because of the upgrade. You can disable locally the `react/display-name` errors.

**Comment by adithyaakrishna** [comment]
@Hyperkid123 The test is failing, and this is the error that I saw in the Travis CI Logs. I was not able to determine why this error is occurring and how to fix this, could you please help me out with this? 😶 

Screenshot 2022-02-25 at 9 58 53 PM

**Comment by Hyperkid123** [comment]
@adithyaakrishna I will take a closer look on Monday. But the work you did is good.

**Comment by adithyaakrishna** [comment]
Okay sure, thanks so much @Hyperkid123 :)
I was able to find the problem. Its something related to the way we are importing RuleTester using require in disallow-fec-relative-imports.test.js

1. https://stackoverflow.com/questions/70960942/the-argument-filename-must-be-a-file-url-object-file-url-string-or-absolute
2. https://github.com/prettier/prettier-eslint-cli/issues/426

**Comment by Hyperkid123** [comment]
@adithyaakrishna I have done some digging around and this issue seems to be only related to the testing environment. Can you please disable this test file `disallow-fec-relative-imports.test.js`? Or allow me to push to your remote.

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
