### PR TITLE
InsightsLabel update & removed unused css

### PR DESCRIPTION
**Pull request by Fewwy**

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]

**Review by gkarat — APPROVED** [review]
👍🏼  lgtm

**Comment by gkarat** [comment]
@Fewwy please fix the lint issue

**Comment by Fewwy** [comment]
@Hyperkid123 Lint issue should be fixed now :)

**Comment by Hyperkid123** [comment]
@Fewwy you wull have to update snapshots after the dependency upgrades.

**Pull request merged**
