### PR TITLE
Migrate inventory to v3

### PR DESCRIPTION
**Pull request by karelhala**

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@karelhala the folder structure is not complete. In order for automatic env selection to work, we need each folder to include index.js which will point to desirable components. This file will be referenced by local `package.json` to switch between cjs/ems on demand.

This applies to any component/function that is "importable". It needs its folder with the same name as the JS file and index.js file that exports it.

**Comment by Hyperkid123** [comment]
@karelhala will you create a manual release?

**Comment by karelhala** [comment]
@Hyperkid123 yup, I'll do that tomorrow

**Review by Hyperkid123 — APPROVED** [review]
After this PR is merged, we should start with cleaning the imports in the whole repo and removing fallback options.

**Pull request merged**
