### PR TITLE
Send all server errors to sentry

### PR DESCRIPTION
**Pull request by karelhala**
Screenshot from 2019-07-31 11-16-50

### CODE REVIEW

**Comment by AllenBW** [comment]
@ryelo is this the kinda catchall we should have in each of the platform apps?

**Comment by karelhala** [comment]
> @ryelo is this the kinda catchall we should have in each of the platform apps?

You should be using axios and this error interceptor so you should be covered.

**Comment by AllenBW** [comment]
Hmm so maybe we ought to stop throwin em at the user here? https://github.com/RedHatInsights/insights-advisor-frontend/blob/a8f8efd65cef96eb71e8b36f6837557a2e5e9f55/src/Store/index.js#L13

**Comment by karelhala** [comment]
Not really, you should still show toast notification message for user so he understands what broke, but at the same time we are sending the error to Sentry so you can see if users are getting errors and which errors.

**Comment by karelhala** [comment]
@ryelo what do you think about that sentryID is it enough or should I also include sentry URL?

**Comment by karelhala** [comment]
Released in new packages [@redhat-cloud-services/frontend-components-utilities/v/0.0.8](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components-utilities/v/0.0.8) and [@redhat-cloud-services/frontend-components-notifications/v/0.0.7](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components-notifications/v/0.0.7)

**Pull request merged**
