### PR TITLE
Match dark-green compliance check icon everywhere

### PR DESCRIPTION
**Pull request by dLobatog**
Screenshot from 2020-04-17 09-06-09

### CODE REVIEW

**Comment by bastilian** [comment]
Let's check with UX(@katierik) if the `<CheckCircleIcon color="green"/>` is the correct color. Policies uses this and it looks mor like the one in the mocks: 

Screenshot 2020-04-17 at 09 15 23

[1] https://github.com/RedHatInsights/policies-ui-frontend/blob/master/src/components/Icons/EnabledPolicyIcon.tsx#L5

**Comment by katierik** [comment]
Looks correct!

**Comment by bastilian** [comment]
@katierik Do you mean the green in @dLobatog's screenshot or mine? The one in Daniel's is the green this PR would change it to. The one in mine is from the custom Policies application(!).

**Comment by katierik** [comment]
@bastilian your screenshot! Didn't realize which app I was looking at!
This is the color in the sketch library: 
image

**Comment by dLobatog** [comment]
@katierik I think the color you have on sketch is wrong. This is the `pf-global--success-color--100` from Patternfly 4. https://www.patternfly.org/v4/documentation/overview/global-css-variables
image.

It's the same color that advisor is using: https://github.com/RedHatInsights/insights-advisor-frontend/blob/1b4de606925fa011e4b87b195f8c3b08d5bc38a8/src/PresentationalComponents/RuleDetails/_RuleDetails.scss#L29 , which is what's being asked on https://projects.engineering.redhat.com/browse/RHICOMPL-585

**Pull request merged**
