### PR TITLE
Add progress bar to sources wizard

### PR DESCRIPTION
**Pull request by rvsia**
TODO
- [x] tests

loading

### CODE REVIEW

**Comment by rvsia** [comment]
@Hyperkid123 That's done by the component.

**Comment by Hyperkid123** [comment]
> @Hyperkid123 That's done by the component.

Can you override it?

**Comment by rvsia** [comment]
I will try

**Comment by rvsia** [comment]
@Hyperkid123 The progress inherits text-align from the empty-state :face_with_thermometer: 

Fixed with `text-align: initial`

loading

(Yeah, this is actually how it should look)

**Comment by Hyperkid123** [comment]
@rvsia i would definitely use text-align: right. This just looks wrong to me :smile:

**Comment by rvsia** [comment]
Yeah, you are right, looks much better

load

(_Maybe it's the right time for maffernfly_)

**Pull request merged**
