### PR TITLE
Remove PF styles from webpack build.

### PR DESCRIPTION
**Pull request by Hyperkid123**
We need a small change in chrome to make sure all styles are provided to the platform.

### CODE REVIEW

**Comment by bastilian** [comment]
Does this mean that patternfly style from applications, included in the packages they depend on, will not be used, or?

**Comment by Hyperkid123** [comment]
> Does this mean that patternfly style from applications, included in the packages they depend on, will not be used, or?

 @bastilian  I've just sent a memo about it. You can find more details there. You were probably not using your specific version anyway. :wink:

**Comment by Hyperkid123** [comment]
Chrome is now ready for this change in all envs.

**Review by rvsia — APPROVED** [review]
Tested in Sources-UI. PF styles were included only 1x.

**Review by karelhala — APPROVED** [review]

**Pull request merged**
