### PR TITLE
Use Patternfly dynamic-modules.json where possible

### PR DESCRIPTION
**Pull request by randomnetcat**
Per [RHCLOUD-32457](https://issues.redhat.com/browse/RHCLOUD-32457).

I have checked that it builds within this repository, but had trouble convincing another repository to link it in.

### CODE REVIEW

**Comment by randomnetcat** [comment]
Ah, tests are failing due to the Patternfly updates. Oops (sorry, I did forget to run those locally). I'll look into that tomorrow.

**Comment by randomnetcat** [comment]
Now fixed.

**Review by Hyperkid123 — COMMENTED** [review]
You need to add the `guess-module.js` and `guess-module.d.ts` into the `.gitignore` file.

**Comment by randomnetcat** [comment]
Fixed, sorry. Renamed that file at the end and forgot to update the gitignore.

**Pull request merged**
