### PR TITLE
Add minified version of build

### PR DESCRIPTION
**Pull request by karelhala**

### CODE REVIEW

**Comment by rvsia** [comment]
Is this also going to minify CSS files?

**Comment by Hyperkid123** [comment]
@karelhala wasn't the terser plugin supposed to minify the code?

**Comment by karelhala** [comment]
@Hyperkid123 it is, but react-dom and other react deps require `NODE_ENV` to be set in order to load correct files. Without this change when `react-dom` was required i loaded `react-dom.development.js` which is like 500 KB.

**Comment by karelhala** [comment]
@rvsia since this will release new version of all packages I've included the minimize option to all rollup configs as well. Good call!

**Pull request merged**
