### PR TITLE
Change perPage to per_page to fix getEntities

### PR DESCRIPTION
**Pull request by rvsia**
This fixes a bug, when the table couldn't be loaded without returning per_page in getEntities function.

(I think we should unify using of camelCase and snake_case across inventory app. :thinking: )

cc @bastilian

### CODE REVIEW

**Comment by bastilian** [comment]
@rvsia Thank you! However there still seems to be something off either with the way the component is used or in the component.

With something like this, the table loads, but it doesn't show any data:

```javascript
import { InventoryTable as FECInventoryTable } from '@redhat-cloud-services/frontend-components/Inventory';

    const getEntities = async (...args) => {
        console.log(...args);
        const { collection: systems, total } = await fetchSystems(); // returns an array of entities
        return {
            results: systems,
            total,
            loaded: true
        };
    };

 <FECInventoryTable
                onLoad={({ mergeWithEntities }) => {
                    getRegistry().register({
                        ...mergeWithEntities()
                    });
                }}
                getEntities={ getEntities } />
```

and the redux state looks like this:

```entities:
activeFilters: []
allTagsLoaded: false
columns: (2) [{…}, {…}]
count: undefined
invConfig: {}
loaded: true
page: 1
perPage: undefined
rows: []
sortBy: {key: "updated", direction: "desc"}
tagsLoaded: false
total: 1```

**Comment by rvsia** [comment]
Not sure what is happening, everything is fine on my end

```jsx
const getEntities = async (...args) => {
    console.log(...args);
    return {
        total: 0,
        results: [
            { id: '123' }
        ]
    };
};
```

```jsx
<InventoryTable
      getEntities={ getEntities }
      onLoad={({ mergeWithEntities, INVENTORY_ACTION_TYPES }) => {
          getRegistry().register({
              ...mergeWithEntities(entitiesReducer(INVENTORY_ACTION_TYPES))
          });
      }}
  />
```

image


Redux

```
activeFilters: []
allTagsLoaded: false
columns: (2) [{…}, {…}]
count: undefined
invConfig: {}
loaded: true
page: 1
perPage: 50
rows: [{…}]
sortBy: {key: "updated", direction: "desc"}
tagsLoaded: false
total: 0
```
Load entities fulfilled

```
meta: {showTags: false}
payload: {total: 0, filters: undefined, sortBy: {…}, results: Array(1), page: 1, …}
type: "LOAD_ENTITIES_FULFILLED"
```

**Comment by bastilian** [comment]
@rvsia Is maybe your `entitiesReducer` reducer returning or filling the store somehow?

**Review by karelhala — APPROVED** [review]

**Comment by rvsia** [comment]
@bastilian changed to

```jsx
  onLoad={({ mergeWithEntities, INVENTORY_ACTION_TYPES }) => {
      getRegistry().register({
          ...mergeWithEntities()
      });
  }}
```

and it still works fine.

**Comment by bastilian** [comment]
@rvsia I pushed what I have here[1].

It's odd there doesn't seem to be any difference in the use. I also tried to remove the loaded prop (which makes it stay in the loading state), and mock the data that fetchSystems would otherwise return, but it still doesn't seem to properly propagate the entities into the inventory store. 

[1] https://github.com/RedHatInsights/compliance-frontend/pull/901/files#diff-d41389c1e49b96059af8df5c978c229a8cc521008bd0ac86a8f71a43ae620473R108

**Comment by rvsia** [comment]
@bastilian I will take a look. :eye:

**Comment by rvsia** [comment]
@bastilian I used the same code I provided before (+ per_page attribute) and it still works fine.

image

```diff
diff --git a/src/SmartComponents/SystemsTable/InventoryTable.js b/src/SmartComponents/SystemsTable/InventoryTable.js
index 7f434a0..7cde614 100644
--- a/src/SmartComponents/SystemsTable/InventoryTable.js
+++ b/src/SmartComponents/SystemsTable/InventoryTable.js
@@ -1,3 +1,4 @@
+/* eslint-disable no-unused-vars */
 import React, { useEffect, useState, useRef, useCallback } from 'react';
 import { withApollo } from '@apollo/react-hoc';
 import PropTypes from 'prop-types';
@@ -23,6 +24,18 @@ import { systemsWithRuleObjectsFailed } from 'Utilities/ruleHelpers';
 import useFilterConfig from 'Utilities/hooks/useFilterConfig';
 import { InventoryTable as FECInventoryTable } from '@redhat-cloud-services/frontend-components/Inventory';
 
+const getEntities = async (...args) => {
+    console.log(...args);
+    return {
+        total: 0,
+        // eslint-disable-next-line camelcase
+        per_page: 1,
+        results: [
+            { id: '123' }
+        ]
+    };
+};
+
 const InventoryTable = ({
     columns,
     showAllSystems,
@@ -126,60 +139,15 @@ const InventoryTable = ({
                 title={ 'The list of systems in this view is different than those that appear in the Inventory. ' +
                     'Only systems currently associated with or reporting against compliance policies are displayed.' } /> }
             <FECInventoryTable
-                { ...systemProps }
                 onLoad={({
                     INVENTORY_ACTION_TYPES,
                     mergeWithEntities
                 }) => {
                     getRegistry().register({
-                        ...mergeWithEntities(
-                            systemsReducer(
-                                INVENTORY_ACTION_TYPES, columns, showAllSystems, policyId
-                            ))
+                        ...mergeWithEntities()
                     });
                 }}
-                fallback={<SkeletonTable colSize={2} rowSize={15} />}
-                tableProps={{
-                    canSelectAll: false
-                }}
-                variant={compact ? TableVariant.compact : ''}
-                ref={inventory}
-                onRefresh={onRefresh}
-                bulkSelect={{
-                    checked: selectedEntities.length > 0 ?
-                        (items?.every(id => selectedEntities?.find((selected) => selected?.id === id)) ? true : null)
-                        : false,
-                    onSelect: onBulkSelect,
-                    count: selectedEntities.length,
-                    label: selectedEntities.length > 0 ? `${ selectedEntities.length } Selected` : undefined
-                }}
-                {...!showAllSystems && {
-                    ...pagination,
-                    isLoaded,
-                    items,
-                    total,
-                    ...conditionalFilter,
-                    ...remediationsEnabled && {
-                        dedicatedAction: <ComplianceRemediationButton
-                            allSystems={ systemsWithRuleObjectsFailed(selectedEntities) }
-                            selectedRules={ [] } />
-                    }
-                }}
-                {...enableExport && {
-                    exportConfig: {
-                        isDisabled: total === 0 && selectedEntities.length === 0,
-                        onSelect: (_, format) => exportFromState(store.getState()?.entities, format)
-                    }
-                }}
-                {...showActions && {
-                    actions: [{
-                        title: 'View in inventory',
-                        onClick: (_event, _index, { id }) => {
-                            const beta = window.location.pathname.split('/')[1] === 'beta';
-                            window.location.href = `${window.location.origin}${beta ? '/beta' : ''}/insights/inventory/${id}`;
-                        }
-                    }]
-                }}
+                getEntities={getEntities}
             />
         </StateViewPart>
     </StateView>;
```

**Comment by bastilian** [comment]
Hm. I'm really not sure what else could be different. this is what I see with the code that I pushed to compliance:

https://user-images.githubusercontent.com/7757/107771645-574b9000-6d3b-11eb-97a0-7dc2c060ef7b.mp4

**Comment by rvsia** [comment]
@bastilian
 
Do you have something linked to compliance?

I just started Compliance frontend with Insights Proxy. No linking, no custom chrome.

**Comment by bastilian** [comment]
@rvsia Yes! There are frontend-components packages linked (react/redux or the likes):

```
 ls -la node_modules/@redhat-cloud-services                                                                                                                                                                               ✔  took 4s  ▓▒░
total 0
drwxr-xr-x     9 bastilian  staff    288 Feb 12 08:17 .
drwxr-xr-x  1051 bastilian  staff  33632 Feb 12 07:52 ..
lrwxr-xr-x     1 bastilian  staff    105 Feb 12 08:17 frontend-components -> ../../../../../../.nvm/versions/node/v10.23.0/lib/node_modules/@redhat-cloud-services/frontend-components
drwxr-xr-x     9 bastilian  staff    288 Feb 12 07:52 frontend-components-config
lrwxr-xr-x     1 bastilian  staff    126 Feb 12 08:17 frontend-components-inventory-compliance -> ../../../../../../.nvm/versions/node/v10.23.0/lib/node_modules/@redhat-cloud-services/frontend-components-inventory-compliance
drwxr-xr-x    16 bastilian  staff    512 Feb 12 07:52 frontend-components-notifications
drwxr-xr-x    16 bastilian  staff    512 Feb 12 07:52 frontend-components-remediations
lrwxr-xr-x     1 bastilian  staff    115 Feb 12 08:17 frontend-components-utilities -> ../../../../../../.nvm/versions/node/v10.23.0/lib/node_modules/@redhat-cloud-services/frontend-components-utilities
drwxr-xr-x    16 bastilian  staff    512 Feb 12 07:52 host-inventory-client
```

**Comment by rvsia** [comment]
@bastilian That could be the issue. Do npm install without links and I think it should work.

**Comment by bastilian** [comment]
@rvsia I tried that just now and same thing. :/ rmrfed node_modules and did a fresh `npm install`.

**Comment by rvsia** [comment]
I am out of ideas, maybe some old cache in browser? You can try to switch to beta (but it worked for me in stable as well).

**Comment by bastilian** [comment]
@rvsia I tried beta as well, same issue also after clearing browser cache. I'll try and dig around more, maybe I'll find waht is wrong on my cursed machine. :D Thank you for taking a look!

**Comment by rvsia** [comment]
@bastilian Just to be sure I went to the same place in the application as you

image

Oh, it's puzzling. Let me know, if you find it out!

**Pull request merged**
