### PR TITLE
Add Bulk select component

### PR DESCRIPTION
**Pull request by karelhala**
### Items in dropdown
Screenshot from 2019-08-27 16-13-38
Screenshot from 2019-08-27 16-15-56
### No items in dropdown
Screenshot from 2019-08-27 16-14-38

### CODE REVIEW

**Comment by karelhala** [comment]
ping @katierik

**Comment by katierik** [comment]
There is a split button component in PF that seems usable for this? 
https://www.patternfly.org/v4/documentation/react/components/dropdown/#split-button

**Comment by AllenBW** [comment]
adding https://github.com/patternfly/patternfly-react/pull/2840 as a related reminder

**Comment by karelhala** [comment]
@katierik yup good point, this is using the split button component. It is just a wrapper so consumers could use this component easier and just pass the things they are required (number of selected items and actions). Now we are waiting for https://github.com/patternfly/patternfly-react/pull/2840 to be merged in order to add the number of selected items in there as well.

**Comment by karelhala** [comment]
Added count in the split button, due to being relatively new feature in PF react core I also had to add catch fallback and show error message in console. So if any app will use this componen and will have outdated PF react core package they can still use this component and will also see error in console to understand why they can't see selected count.

**Comment by karelhala** [comment]
@ryelo sure thing!

**Comment by karelhala** [comment]
Released in new version [@redhat-cloud-services/frontend-components/v/0.0.12](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components/v/0.0.12)

**Pull request merged**
