### PR TITLE
added helper function to get relative time

### PR DESCRIPTION
**Pull request by mkholjuraev**
Helper function to get relative time which is suggested  by PatternFly. https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology

### CODE REVIEW

**Comment by karelhala** [comment]
We already have a component for this. Look at [`DateFormat`](https://github.com/RedHatInsights/frontend-components/blob/master/packages/components/src/Components/DateFormat/DateFormat.js). It's a component that wraps this whole thing. By default it uses `relative` format so you get the date calculated from curr date. You don't have to pass the initial date in there, however if that's what you need I would prefer updating that component with new prop, something like `fromDate`. Also if you need just to calculate the date and perhaps send to server we could expose functions that does that for you.

**Comment by mkholjuraev** [comment]
@karelhala I would appreciate if you can tell me how to import DateFormat into the project.

**Comment by karelhala** [comment]
@mkholjuraev `npm i -S @redhat-cloud-services/frontend-components` to install frontend components. Once you install them you can use the `DateFormat` component wherever you need by importing it 
```JSX
import React from 'react';
import { DateFormat } from '@redhat-cloud-services/frontend-components'
const MyCmp = () => {
  <div>
    <DateFormat date={new Date()} />
  </div>
}
```

**Comment by PanSpagetka** [comment]
You can import and use it like this:
```
import { DateFormat } from '@redhat-cloud-services/frontend-components';
...
 <DateFormat type='relative'  date='Aug 31 2019 UTC' />
```

You can provide Date object, string or number as a date.
More details here: https://cloud.redhat.com/docs/storybook?path=/story/components--dateformat

**Comment by mkholjuraev** [comment]
I tried these already, but I am getting following error:

Uncaught (in promise) Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by karelhala** [comment]
What version of Frontend-components do you have? You might need to update to more recent one.

**Comment by mkholjuraev** [comment]
I was using 0.0.29. I updated it. Everything is working now thank you!

**Pull request closed without merging**
