### PR TITLE
Make edit link universal

### PR DESCRIPTION
**Pull request by rvsia**
- EditButton should work when wizard is used outside sources
- fixed obsolete link to `hybrid`
- small refactoring to make the code more beautiful 

todo:
- [x] tests

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@rvsia :test_tube: :boom:

**Comment by rvsia** [comment]
@Hyperkid123 locally tests are passing :man_shrugging: I will try to update package-lock and see if that is going to help.

**Comment by Hyperkid123** [comment]
@rvsia some unhandled async call:

 FAIL  packages/sources/src/tests/addSourceWizard/finalWizard.test.js
  ● Final wizard › removes source on errored step correctly - when unavailable
    connect ECONNREFUSED 127.0.0.1:80

**Comment by rvsia** [comment]
@Hyperkid123 The failing is caused by other repos as theirs endpoints are not mocked and they are not waiting until promises finish.... :disappointed:  So, I mocked API calls in TagsModal to pass these tests. Hopefully it will help. :pray:

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
