### PR TITLE
Show operating system in label

### PR DESCRIPTION
**Pull request by rvsia**
Screenshot 2021-04-21 at 14 05 39
Screenshot 2021-04-21 at 14 05 48

### CODE REVIEW

**Comment by bastilian** [comment]
Would it be possible to move the Operating Systems Label component to frontend-components?

We added a similar component to compliance[0]. If we had a common label component we could make sure the OS version colors match across the platform. 

[0] https://github.com/RedHatInsights/compliance-frontend/blob/master/src/PresentationalComponents/OperatingSystemBadge/OperatingSystemBadge.js

**Comment by karelhala** [comment]
@bastilian if you are using inventory component you should show the OS release from inventory table, no need to write custom one. Unless you want to show the Os release badge in some other table.

**Comment by bastilian** [comment]
@karelhala We also show the Label in other none InventoryTable places.

**Comment by karelhala** [comment]
@bastilian oooh, yeah we can def move it to components repo as well. For now we're going to keep it in inventory so this feature is released ASAP and we can move this feature to FEC afterwards.

**Review by karelhala — APPROVED** [review]

**Comment by rvsia** [comment]
I would also say this is still a WIP design and it could mess other applications designs. Maybe we should do some iterations before we make it shared.

**Pull request merged**
