### PR TITLE
Fix notifications babel config for direct imports

### PR DESCRIPTION
**Pull request by elad661**
Many parts of the documentation suggests importing the `addNotification` action directly.

However, that didn't work with the babel-plugin-transform-imports configuration offered in the README file.
This commit fixes the documented configuration to allow direct import of `addNotification` and `removeNotification`.

cc: @karelhala

### CODE REVIEW

**Comment by elad661** [comment]
Ugh, looks like while this suggested change fixes the import of `{ addNotification }`, it breaks the import of the `{ notifications }` reducer due to the `skipDefaultConversion` flag - it tries to import the name `notifications` from `notifications.js` instead of using the default.

I'm still trying to find ways to make this work, but I'm not sure that's possible without changing the exports structure. Any ideas?

**Comment by karelhala** [comment]
@elad661 thanks for taking a lookg at this! I think that the best way here is to add additional export to notifications reducer and remove `skipDefaultConversion` from the docs.
```diff
diff --git a/packages/notifications/src/redux/reducers/notifications.js b/packages/notifications/src/redux/reducers/notifications.js
index 76e64714..aacd33a4 100644
--- a/packages/notifications/src/redux/reducers/notifications.js
+++ b/packages/notifications/src/redux/reducers/notifications.js
@@ -26,4 +26,6 @@ export const notificationsReducers = {
     [CLEAR_NOTIFICATIONS]: clearNotifications
 };
 
-export default applyReducerHash(notificationsReducers, defaultState);
+export const notifications = applyReducerHash(notificationsReducers, defaultState);
+
+export default notifications;
```

**Comment by elad661** [comment]
Thanks @karelhala, I updated the commit accordingly

**Comment by karelhala** [comment]
Build passed, travis just won't update the status... https://travis-ci.org/github/RedHatInsights/frontend-components/builds/704241129

**Pull request merged**
