### PR TITLE
Change "Clear filters" to "Reset filters" according to UXD

### PR DESCRIPTION
**Pull request by katerinapat**
Change wording according to 
https://docs.google.com/document/d/1lwG_D41-KhEBjZPxJvbOFKkpwmTN9FmWC7krkMrYOZI/edit#

### CODE REVIEW

**Comment by bastilian** [comment]
Wouldn't "Reset" mean to go back to the initial/default filters rather than clearing them?

**Comment by katerinapat** [comment]
> Wouldn't "Reset" mean to go back to the initial/default filters rather than clearing them?

@bastilian exactly. Based on the documents from UXD all the apps should adapt this behavior.

**Comment by karelhala** [comment]
@katerinapat we've had a few days back discussion with UXers about it as well, the problem is that upon clicking on "Reset filters" the filter has to go back to original state. So apps has to adapt to this behavior once they start using the reset, moreover not all filters has default values. For instance global filter doesn't really have default state and there should still be "Remove filters". Hence I wouldn't just change the string in here, but rather pass in new prop `clearTitle` which would be a node propType and by default it would be `Remove filter` (we want to make it backward compatible).

**Comment by mkholjuraev** [comment]
I am wondering if there is an agreement on what to do. We have a blocked ticket associated with changing 'Clear Filters' to 'Reset filters' which is done in this PR.

**Comment by bastilian** [comment]
@mkholjuraev I think what needs to be done for this is to make sure that all behaviours align with the wording in all places. The `FilterChips` component is used in a few applications and other components where this might not be the case yet. 

Maybe the change in this PR should just allow to pass in or choose a wording?

**Comment by karelhala** [comment]
Closing this in favor of https://github.com/RedHatInsights/frontend-components/pull/1035, we want to preserve current behavior and allow consumers to pass in custom delete string. This is because some tables are not ready to reset filters or will never be.

**Pull request closed without merging**
