### PR TITLE
fix(proxy): don't use agent for routes

### PR DESCRIPTION
**Pull request by redallen**
Using `agent` and `onProxyReq` crashes with this:
```sh
_http_outgoing.js:561
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ClientRequest.setHeader (_http_outgoing.js:561:11)
    at ProxyServer.cookieTransform (/home/akofink/dev/repos/compliance-frontend/node_modules/@redhat-cloud-services/frontend-components-config-utilities/cookieTransform.js:48:18)
    at ProxyServer.emit (/home/akofink/dev/repos/compliance-frontend/node_modules/eventemitter3/index.js:184:35)
    at ClientRequest.<anonymous> (/home/akofink/dev/repos/compliance-frontend/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:133:16)
    at ClientRequest.emit (events.js:412:35)
    at tickOnSocket (_http_client.js:784:7)
    at onSocketNT (_http_client.js:823:5)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

### CODE REVIEW

**Review by akofink — APPROVED** [review]
Thanks! Works well. Nit: we could expose an env variable perhaps to make it configurable? Not sure if anyone needs the proxy to a local route (probably not).

**Comment by redallen** [comment]
If they were to try to proxy through the corporate proxy to a local route it would crash with the above error. It's a known upstream problem that would take picking apart networking internals on our side: https://github.com/http-party/node-http-proxy/issues/1287

I think we can add the option in the future if there's demand, but currently demand is low and cost is high.

**Comment by akofink** [comment]
Still an ACK from me :) Thanks again, @redallen!

**Comment by Hyperkid123** [comment]
@redallen are we good to merge this?

**Review by rvsia — APPROVED** [review]

**Comment by redallen** [comment]
@Hyperkid123 Yep, good to merge!

**Pull request merged**
