### PR TITLE
fix(ComplianceEmptyState): RHICOMPL-744 wrapped primary button

### PR DESCRIPTION
**Pull request by skateman**
The primary button in the compliance empty state wasn't wrapped in the `EmptyStatePrimary` component, so its padding was not set properly.

### CODE REVIEW

**Review by AllenBW — APPROVED** [review]
👍 ⚡ looks to wrap the main button in the emptystateprimary 🙊

**Review by akofink — APPROVED** [review]
:+1: 

Before:
image

After:
image

**Comment by AllenBW** [comment]
@skateman i like seein yer face here 🤗

**Comment by AllenBW** [comment]
ooo @skateman gotta update those snapshots yo

**Pull request merged**
