### PR TITLE
AddSourceWizard select application first

### PR DESCRIPTION
**Pull request by rvsia**
**Description**

Combines SourceType and AppType selection to one screen with dynamic limitation.

Prepares to AddSourceWizard to use in different applications:
- new options to customize the form (initialValues, disable app selection)

Hide application selection in the summary (for edit form variant, where user is not selecting the app)

Little fixes, updates of readme, etc.

sourceTypesSelection

**TODO**
- [x] tests
- [x] docs

@terezanovotna @gtanzillo

### CODE REVIEW

**Comment by terezanovotna** [comment]
Nice! We will have to add a message why some applications cannot be added, so the user is not confused.

**Comment by rvsia** [comment]
@terezanovotna I added a `Selected application will limit the options of available source types.` message bottom the first selection,  how should I change it?

**Comment by rvsia** [comment]
@karelhala Test failure doesn't seem to be related with this PR.

**Comment by karelhala** [comment]
@rvsia good point. This PR https://github.com/RedHatInsights/frontend-components/pull/154 should fix failing tests.

**Comment by karelhala** [comment]
This PR has been included in npm package version [@redhat-cloud-services/frontend-components-sources/v/0.0.8](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components-sources/v/0.0.8)

**Pull request merged**
