### PR TITLE
Add an initial stab at component testing

### PR DESCRIPTION
**Pull request by rsnyman**
- Create a Cypress configuration for the "components" folder
- Create two simple tests for the DownloadButton
- Fix up a component's import that was conflicting with Webpack

### CODE REVIEW

**Comment by rsnyman** [comment]
@Hyperkid123 let me know what you think.

**Comment by Hyperkid123** [comment]
@rsnyman the config looks good. You have just some linting issues that can be fixed via `npm run lint --fix`. Have you managed to actually start the test run?

**Comment by rsnyman** [comment]
@Hyperkid123 Yep, I'll get onto those linting issues. Yes, I have run it :-)

**Review by Hyperkid123 — APPROVED** [review]
@rsnyman code looks good. Let me know if this is good to go or if you want to add some additional changes.

**Comment by rsnyman** [comment]
I'm happy for now, we can merge this, and I can work on some more tests in another PR.

**Pull request merged**
