### PR TITLE
Add custom form components to be used in DDF

### PR DESCRIPTION
**Pull request by karelhala**
These components will later be used in settings and user preferences. We want to share similiar components between multiple repositories.

### CODE REVIEW

**Comment by karelhala** [comment]
ping @Hyperkid123 @rvsia

**Comment by karelhala** [comment]
@Hyperkid123 migration to new version of DDF can happen seperately. I'd prefer releasing these components in older version as well, so we have some fallback. Perform upgrade in all places where we use DDF (user preferences and settings currently) and upgrade these (FEC) components after that.

**Comment by Hyperkid123** [comment]
@karelhala :+1: but you should keep it in mind that the migration should happen sooner rather than later. We still support v1, but we will stop eventually.

**Comment by Hyperkid123** [comment]
@karelhala this does not seem to be relevant anymore. Re-open if you disagree.

**Pull request closed without merging**
