### PR TITLE
Add Conditional filter component

### PR DESCRIPTION
**Pull request by karelhala**
RHCLOUD-2174

peek27Z86Z
peekJV226Z

### On wider screens
Screenshot from 2019-09-03 16-32-43
Screenshot from 2019-09-03 16-32-49
Screenshot from 2019-09-03 16-32-54

### On smaller screens
Screenshot from 2019-09-03 16-33-36
Screenshot from 2019-09-03 16-33-41

### CODE REVIEW

**Comment by karelhala** [comment]
ping @katierik

**Comment by katierik** [comment]
Awesome!

Small UI updates:
Xnip2019-09-03_09-51-20

**Comment by karelhala** [comment]
@katierik great feedback! Thank you. I've also made the first dropdown static width and on small creens only the icon is visible.

peek27Z86Z
peekJV226Z

**Comment by katierik** [comment]
Fabulous. 👍

**Comment by ryelo** [comment]
@karelhala I'm going to review this today. Can you update the storybook to show this too?

**Comment by karelhala** [comment]
@ryelo sure thing! And good point.

**Comment by karelhala** [comment]
Released in new version [@redhat-cloud-services/frontend-components/v/0.0.12](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components/v/0.0.12)

**Pull request merged**
